### ISSUE TITLE
Fix comments

### ISSUE THREAD

**Issue by AndreaOrru** [ziglang/zig-mode#5]

**Comment by mdsteele** [comment]
Not sure which comment issues are in scope here, but a couple specific things I've run into:
* [ ] Commands like `M-x comment-region` and `M-x comment-dwim` use C-style `/**/` comments instead of Zig-style `//` comments
* [ ] Doc comments (`///`) currently use `font-lock-comment-face`, but they should probably use `font-lock-doc-face` instead.
